[package]
name = "server"
version = "0.1.0"
edition.workspace = true
license = "MIT"

[dependencies]
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true

# Local-only dependencies
axum = "0.8.6"
tokio-modbus = { version = "0.17.0", default-features = false, features = ["rtu"] }
tokio-serial = "5.4.5"
config = "0.15.18"
toml = "0.9.8"